const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'app', 'page.tsx');

const lines = [];
lines.push(`"use client";`);
lines.push(`import { useEffect, useState } from "react";`);
lines.push(`import Link from "next/link";`);
lines.push(`import Image from "next/image";`);
lines.push(`import { useAuth } from "@/context/AuthProvider";`);
lines.push(`import api from "@/lib/api";`);
lines.push(`import {`);
lines.push(`  ShieldCheck, Star, MapPin, ArrowRight, CheckCircle2, Users,`);
lines.push(`  ClipboardList, LogIn, UserPlus, Phone,`);
lines.push(`  Award, Menu, X,`);
lines.push(`} from "lucide-react";`);
lines.push(``);
lines.push(`interface Category {`);
lines.push(`  id: string;`);
lines.push(`  name: string;`);
lines.push(`  nameUz: string;`);
lines.push(`  nameRu: string;`);
lines.push(`  icon: string | null;`);
lines.push(`  _count?: { masters: number };`);
lines.push(`}`);
lines.push(``);
lines.push(`// Kategoriya nomiga mos GIF icon mapping`);
lines.push(`const categoryGifs: Record<string, string> = {`);
lines.push(`  "Santexnika": "/plumber.gif",`);
lines.push(`  "Elektrik": "/electric.gif",`);
lines.push(`  "Duradgor": "/carpentry.gif",`);
lines.push(`  "Konditsioner": "/air-conditioner.gif",`);
lines.push(`  "Qurilish": "/encryption.gif",`);
lines.push(`  "Bo'yoqchi": "/paint-roller.gif",`);
lines.push(`  "Gazchi": "/gas worker.gif",`);
lines.push(`  "Uy ta'mirlash": "/home repair.gif",`);
lines.push(`  "Deraza o'rnatish": "/window installation.gif",`);
lines.push(`  "Tom yopish": "/roofing.gif",`);
lines.push(`  "Plitka yotqizish": "/laying tiles.gif",`);
lines.push(`  "Gipsokarton": "/plasterboard.gif",`);
lines.push(`  "Suvoq ishlari": "/trowel.gif",`);
lines.push(`  "Pol yotqizish": "/floor laying.gif",`);
lines.push(`  "Issiqlik tizimi": "/heating system.gif",`);
lines.push(`  "Eshik o'rnatish": "/carpentry.gif",`);
lines.push(`  "Suv tozalash": "/water purification.gif",`);
lines.push(`  "Kamera o'rnatish": "/camera installation.gif",`);
lines.push(`  "Devor qog'ozi": "/wallpaper.gif",`);
lines.push(`  "Parda o'rnatish": "/curtain installation.gif",`);
lines.push(`  "Payvandlash": "/welding.gif",`);
lines.push(`  "Loyiha va smeta": "/project and estimate.gif",`);
lines.push(`  "Hovuz qurilishi": "/pool pennies.gif",`);
lines.push(`  "Maishiy texnika": "/home-appliance.gif",`);
lines.push(`  "Tozalash": "/cleaning.gif",`);
lines.push(`  "Kalit usta": "/encryption.gif",`);
lines.push(`  "Dezinfeksiya": "/cleaning.gif",`);
lines.push(`  "Mebel yig'ish": "/carpentry.gif",`);
lines.push(`  "Ko'chirish": "/home repair.gif",`);
lines.push(`  "Lift ta'mirlash": "/home repair.gif",`);
lines.push(`  "Internet va tarmoq": "/camera installation.gif",`);
lines.push(`  "Kompyuter ta'mirlash": "/home-appliance.gif",`);
lines.push(`  "Telefon ta'mirlash": "/home-appliance.gif",`);
lines.push(`  "Avtomobil ta'mirlash": "/home repair.gif",`);
lines.push(`  "Bog' ishlari": "/cleaning.gif",`);
lines.push(`};`);
lines.push(``);
lines.push(`function getCategoryGif(name: string): string {`);
lines.push(`  return categoryGifs[name] || "/home repair.gif";`);
lines.push(`}`);
lines.push(``);
lines.push(`const defaultServices = [`);
lines.push(`  { id: "santexnika", nameUz: "Santexnika", gif: "/plumber.gif", desc: "Kran, truba, kanalizatsiya" },`);
lines.push(`  { id: "elektrik", nameUz: "Elektrik", gif: "/electric.gif", desc: "Rozetka, simlar, avtomat" },`);
lines.push(`  { id: "konditsioner", nameUz: "Konditsioner", gif: "/air-conditioner.gif", desc: "O'rnatish, tozalash, ta'mirlash" },`);
lines.push(`  { id: "duradgor", nameUz: "Duradgor", gif: "/carpentry.gif", desc: "Eshik, mebel, yog'och ishlari" },`);
lines.push(`  { id: "qurilish", nameUz: "Qurilish", gif: "/encryption.gif", desc: "Ta'mirlash, suvoq, g'isht" },`);
lines.push(`  { id: "boyoqchi", nameUz: "Bo'yoqchi", gif: "/paint-roller.gif", desc: "Devor, shift, fasad bo'yash" },`);
lines.push(`  { id: "gazchi", nameUz: "Gazchi", gif: "/gas worker.gif", desc: "Gaz plita, kotel, quvur" },`);
lines.push(`  { id: "uyTamir", nameUz: "Uy ta'mirlash", gif: "/home repair.gif", desc: "Umumiy remont ishlari" },`);
lines.push(`];`);
lines.push(``);
lines.push(`const completedWorks = [`);
lines.push(`  { title: "Kran almashtirish", master: "Sardor U.", category: "Santexnika", rating: 5, location: "Toshkent, Chilonzor" },`);
lines.push(`  { title: "Rozetka o'rnatish", master: "Jasur K.", category: "Elektrik", rating: 5, location: "Toshkent, Yunusobod" },`);
lines.push(`  { title: "Devor bo'yash", master: "Rustam M.", category: "Remont", rating: 4, location: "Samarqand" },`);
lines.push(`  { title: "Konditsioner ta'mirlash", master: "Sherzod T.", category: "Konditsioner", rating: 5, location: "Toshkent, Mirzo Ulug'bek" },`);
lines.push(`  { title: "Truba tuzatish", master: "Otabek N.", category: "Santexnika", rating: 5, location: "Buxoro" },`);
lines.push(`  { title: "Qulf almashtirish", master: "Bobur A.", category: "Umumiy", rating: 4, location: "Namangan" },`);
lines.push(`];`);
lines.push(``);
lines.push(`const stats = [`);
lines.push(`  { label: "Ustalar", value: "500+", icon: "/plumber.gif" },`);
lines.push(`  { label: "Bajarilgan ishlar", value: "10,000+", icon: "/home repair.gif" },`);
lines.push(`  { label: "Shaharlarda", value: "14", icon: "/encryption.gif" },`);
lines.push(`  { label: "O'rtacha baho", value: "4.8", icon: "/electric.gif" },`);
lines.push(`];`);
lines.push(``);
lines.push(`export default function LandingPage() {`);
lines.push(`  const { user, token } = useAuth();`);
lines.push(`  const [categories, setCategories] = useState<Category[]>([]);`);
lines.push(`  const [mobileMenu, setMobileMenu] = useState(false);`);
lines.push(``);
lines.push(`  useEffect(() => {`);
lines.push(`    api.get("/categories").then((r) => setCategories(r.data)).catch(() => {});`);
lines.push(`  }, []);`);
lines.push(``);
lines.push(`  return (`);
lines.push(`    <div className="min-h-screen bg-white dark:bg-gray-900">`);
lines.push(`      {/* ===== HEADER ===== */}`);
lines.push(`      <header className="sticky top-0 z-50 bg-white dark:bg-gray-900/80 backdrop-blur-lg border-b border-gray-100 dark:border-gray-800">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-16">`);
lines.push(`          <Link href="/" className="flex items-center gap-2">`);
lines.push(`            <img src="/logo.png" alt="Online Usta" className="object-contain h-9 w-auto logo-dark" />`);
lines.push(`            <span className="font-bold text-lg sm:text-xl text-gray-900 dark:text-white">Online Usta</span>`);
lines.push(`          </Link>`);
lines.push(`          <nav className="hidden md:flex items-center gap-6 text-sm font-medium text-gray-600 dark:text-gray-300">`);
lines.push(`            <a href="#categories" className="hover:text-blue-600 transition">Xizmatlar</a>`);
lines.push(`            <a href="#works" className="hover:text-blue-600 transition">Bajarilgan ishlar</a>`);
lines.push(`            <a href="#how" className="hover:text-blue-600 transition">Qanday ishlaydi</a>`);
lines.push(`          </nav>`);
lines.push(`          <div className="hidden md:flex items-center gap-3">`);
lines.push(`            {token && user ? (`);
lines.push(`              <Link href={user.role === "ADMIN" ? "/admin" : user.role === "MASTER" ? "/master" : "/home"} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-blue-700 transition">`);
lines.push(`                <ClipboardList className="w-4 h-4" />`);
lines.push(`                Kabinetga kirish`);
lines.push(`              </Link>`);
lines.push(`            ) : (`);
lines.push(`              <>`);
lines.push(`                <Link href="/auth/login" className="flex items-center gap-1.5 text-gray-700 dark:text-gray-300 hover:text-blue-600 px-3 py-2 rounded-xl text-sm font-medium transition">`);
lines.push(`                  <LogIn className="w-4 h-4" /> Kirish`);
lines.push(`                </Link>`);
lines.push(`                <Link href="/auth/register" className="flex items-center gap-1.5 bg-blue-600 text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-blue-700 transition">`);
lines.push(`                  <UserPlus className="w-4 h-4" /> Ro'yxatdan o'tish`);
lines.push(`                </Link>`);
lines.push(`              </>`);
lines.push(`            )}`);
lines.push(`          </div>`);
lines.push(`          <button className="md:hidden w-9 h-9 flex items-center justify-center rounded-xl text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 transition" onClick={() => setMobileMenu(!mobileMenu)}>`);
lines.push(`            {mobileMenu ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}`);
lines.push(`          </button>`);
lines.push(`        </div>`);
lines.push(`        {mobileMenu && (`);
lines.push(`          <div className="md:hidden border-t border-gray-100 dark:border-gray-800 bg-white dark:bg-gray-900/95 backdrop-blur-lg pb-4 pt-2 px-4 space-y-1">`);
lines.push(`            <a href="#categories" onClick={() => setMobileMenu(false)} className="block px-3 py-2.5 rounded-xl text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800">Xizmatlar</a>`);
lines.push(`            <a href="#works" onClick={() => setMobileMenu(false)} className="block px-3 py-2.5 rounded-xl text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800">Bajarilgan ishlar</a>`);
lines.push(`            <a href="#how" onClick={() => setMobileMenu(false)} className="block px-3 py-2.5 rounded-xl text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800">Qanday ishlaydi</a>`);
lines.push(`            <div className="border-t border-gray-100 dark:border-gray-800 pt-2 mt-2 space-y-1">`);
lines.push(`              {token && user ? (`);
lines.push(`                <Link href={user.role === "ADMIN" ? "/admin" : user.role === "MASTER" ? "/master" : "/home"} onClick={() => setMobileMenu(false)} className="flex items-center gap-2 px-3 py-2.5 rounded-xl text-sm font-semibold text-blue-600 hover:bg-blue-50 dark:hover:bg-gray-800">`);
lines.push(`                  <ClipboardList className="w-4 h-4" /> Kabinetga kirish`);
lines.push(`                </Link>`);
lines.push(`              ) : (`);
lines.push(`                <>`);
lines.push(`                  <Link href="/auth/login" onClick={() => setMobileMenu(false)} className="flex items-center gap-2 px-3 py-2.5 rounded-xl text-sm font-medium text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-800">`);
lines.push(`                    <LogIn className="w-4 h-4" /> Kirish`);
lines.push(`                  </Link>`);
lines.push(`                  <Link href="/auth/register" onClick={() => setMobileMenu(false)} className="flex items-center gap-2 px-3 py-2.5 rounded-xl text-sm font-semibold text-blue-600 hover:bg-blue-50 dark:hover:bg-gray-800">`);
lines.push(`                    <UserPlus className="w-4 h-4" /> Ro'yxatdan o'tish`);
lines.push(`                  </Link>`);
lines.push(`                </>`);
lines.push(`              )}`);
lines.push(`            </div>`);
lines.push(`          </div>`);
lines.push(`        )}`);
lines.push(`      </header>`);
lines.push(``);
lines.push(`      {/* ===== HERO ===== */}`);
lines.push(`      <section className="relative overflow-hidden bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-800 text-white">`);
lines.push(`        <div className="absolute inset-0 opacity-10">`);
lines.push(`          <div className="absolute top-10 left-10 w-72 h-72 bg-white/10 rounded-full blur-3xl" />`);
lines.push(`          <div className="absolute bottom-10 right-10 w-96 h-96 bg-blue-300 rounded-full blur-3xl" />`);
lines.push(`        </div>`);
lines.push(`        <div className="max-w-7xl mx-auto px-4 py-12 sm:py-20 lg:py-28 relative z-10">`);
lines.push(`          <div className="max-w-2xl">`);
lines.push(`            <div className="inline-flex items-center gap-2 bg-white/15 backdrop-blur px-3 sm:px-4 py-1.5 rounded-full text-xs sm:text-sm font-medium mb-4 sm:mb-6">`);
lines.push(`              <ShieldCheck className="w-4 h-4" /> Ishonchli va tezkor xizmat`);
lines.push(`            </div>`);
lines.push(`            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold leading-tight mb-3 sm:mb-4">`);
lines.push(`              Ishonchli usta &mdash; <br />bir necha daqiqada`);
lines.push(`            </h1>`);
lines.push(`            <p className="text-base sm:text-lg text-blue-100 mb-6 sm:mb-8 max-w-lg">`);
lines.push(`              O&apos;zbekiston bo&apos;ylab 500+ ta tasdiqlangan usta. Santexnik, elektrik, ta&apos;mirlovchi &mdash; har qanday muammoga yechim topamiz.`);
lines.push(`            </p>`);
lines.push(`            <div className="flex flex-col sm:flex-row flex-wrap gap-3">`);
lines.push(`              <Link href="/auth/register" className="inline-flex items-center justify-center gap-2 bg-white text-blue-700 font-semibold px-6 py-3 rounded-xl hover:bg-blue-50 transition shadow-lg shadow-blue-900/20 text-sm sm:text-base">`);
lines.push(`                Buyurtma berish <ArrowRight className="w-4 h-4" />`);
lines.push(`              </Link>`);
lines.push(`              <Link href="/auth/register?role=master" className="inline-flex items-center justify-center gap-2 bg-white/15 backdrop-blur text-white font-semibold px-6 py-3 rounded-xl hover:bg-white/25 transition border border-white/20 text-sm sm:text-base">`);
lines.push(`                <img src="/plumber.gif" alt="" className="w-5 h-5" /> Usta sifatida ishlash`);
lines.push(`              </Link>`);
lines.push(`            </div>`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== STATS ===== */}`);
lines.push(`      <section className="bg-white dark:bg-gray-900 border-b border-gray-100 dark:border-gray-800">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4 py-6 sm:py-10">`);
lines.push(`          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">`);
lines.push(`            {stats.map((s, i) => (`);
lines.push(`              <div key={i} className="flex items-center gap-3 sm:gap-4">`);
lines.push(`                <div className="w-10 h-10 sm:w-12 sm:h-12 bg-blue-50 dark:bg-blue-900/30 rounded-xl flex items-center justify-center shrink-0">`);
lines.push(`                  <img src={s.icon} alt={s.label} className="w-7 h-7 sm:w-8 sm:h-8 object-contain" />`);
lines.push(`                </div>`);
lines.push(`                <div>`);
lines.push(`                  <p className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white">{s.value}</p>`);
lines.push(`                  <p className="text-xs sm:text-sm text-gray-500 dark:text-gray-400">{s.label}</p>`);
lines.push(`                </div>`);
lines.push(`              </div>`);
lines.push(`            ))}`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== CATEGORIES ===== */}`);
lines.push(`      <section id="categories" className="bg-gray-50 dark:bg-gray-950 py-10 sm:py-16">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4">`);
lines.push(`          <div className="text-center mb-8 sm:mb-10">`);
lines.push(`            <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-2">Xizmat turlari</h2>`);
lines.push(`            <p className="text-gray-500 dark:text-gray-400 text-sm sm:text-base">O&apos;zingizga kerakli sohani tanlang</p>`);
lines.push(`          </div>`);
lines.push(`          {categories.length > 0 ? (`);
lines.push(`            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3 sm:gap-4">`);
lines.push(`              {categories.map((cat) => (`);
lines.push(`                <Link key={cat.id} href={\`/categories/\${cat.id}\`} className="group bg-white dark:bg-gray-900 rounded-2xl p-4 sm:p-5 shadow-sm hover:shadow-lg transition-all duration-200 text-center border border-gray-100 dark:border-gray-800 hover:border-blue-200 dark:hover:border-blue-800 hover:-translate-y-1">`);
lines.push(`                  <div className="w-14 h-14 sm:w-16 sm:h-16 mx-auto mb-2 sm:mb-3 bg-blue-50 dark:bg-blue-900/30 group-hover:bg-blue-100 dark:group-hover:bg-blue-900/50 rounded-2xl flex items-center justify-center transition overflow-hidden">`);
lines.push(`                    <img src={getCategoryGif(cat.nameUz || cat.name)} alt={cat.nameUz || cat.name} className="w-10 h-10 sm:w-11 sm:h-11 object-contain" />`);
lines.push(`                  </div>`);
lines.push(`                  <h3 className="font-semibold text-gray-900 dark:text-white text-sm">{cat.nameUz || cat.name}</h3>`);
lines.push(`                  {cat._count && <p className="text-xs text-gray-400 mt-1">{cat._count.masters} ta usta</p>}`);
lines.push(`                </Link>`);
lines.push(`              ))}`);
lines.push(`            </div>`);
lines.push(`          ) : (`);
lines.push(`            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3 sm:gap-4">`);
lines.push(`              {defaultServices.map((svc) => (`);
lines.push(`                <Link key={svc.id} href="/categories" className="group bg-white dark:bg-gray-900 rounded-2xl p-4 sm:p-5 shadow-sm hover:shadow-lg transition-all duration-200 border border-gray-100 dark:border-gray-800 hover:border-blue-200 dark:hover:border-blue-800 hover:-translate-y-1">`);
lines.push(`                  <div className="w-14 h-14 sm:w-16 sm:h-16 mb-2 sm:mb-3 mx-auto bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/30 dark:to-indigo-900/30 group-hover:from-blue-100 group-hover:to-indigo-100 rounded-2xl flex items-center justify-center transition overflow-hidden">`);
lines.push(`                    <img src={svc.gif} alt={svc.nameUz} className="w-10 h-10 sm:w-11 sm:h-11 object-contain" />`);
lines.push(`                  </div>`);
lines.push(`                  <h3 className="font-semibold text-gray-900 dark:text-white text-sm text-center">{svc.nameUz}</h3>`);
lines.push(`                  <p className="text-xs text-gray-400 mt-1 text-center">{svc.desc}</p>`);
lines.push(`                </Link>`);
lines.push(`              ))}`);
lines.push(`            </div>`);
lines.push(`          )}`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== HOW IT WORKS ===== */}`);
lines.push(`      <section id="how" className="bg-white dark:bg-gray-900 py-10 sm:py-16">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4">`);
lines.push(`          <div className="text-center mb-8 sm:mb-10">`);
lines.push(`            <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-2">Qanday ishlaydi?</h2>`);
lines.push(`            <p className="text-gray-500 dark:text-gray-400 text-sm sm:text-base">3 oddiy qadam</p>`);
lines.push(`          </div>`);
lines.push(`          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 sm:gap-8">`);
lines.push(`            {[`);
lines.push(`              { step: "01", gif: "/electric.gif", title: "Ro'yxatdan o'ting", desc: "Telefon raqamingiz bilan tez va oson ro'yxatdan o'ting" },`);
lines.push(`              { step: "02", gif: "/project and estimate.gif", title: "Buyurtma bering", desc: "Muammoni yozing, rasm yuklang va qulay vaqtni tanlang" },`);
lines.push(`              { step: "03", gif: "/plumber.gif", title: "Usta keladi", desc: "Tasdiqlangan usta sizning manzilingizga keladi va muammoni hal qiladi" },`);
lines.push(`            ].map((item) => (`);
lines.push(`              <div key={item.step} className="text-center">`);
lines.push(`                <div className="w-20 h-20 mx-auto mb-4 bg-gradient-to-br from-blue-100 to-indigo-100 dark:from-blue-900/40 dark:to-indigo-900/40 rounded-2xl flex items-center justify-center shadow-lg overflow-hidden">`);
lines.push(`                  <img src={item.gif} alt={item.title} className="w-14 h-14 object-contain" />`);
lines.push(`                </div>`);
lines.push(`                <span className="text-xs font-bold text-blue-600 uppercase tracking-wider">Qadam {item.step}</span>`);
lines.push(`                <h3 className="text-lg font-bold text-gray-900 dark:text-white mt-1 mb-2">{item.title}</h3>`);
lines.push(`                <p className="text-gray-500 dark:text-gray-400 text-sm">{item.desc}</p>`);
lines.push(`              </div>`);
lines.push(`            ))}`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== COMPLETED WORKS ===== */}`);
lines.push(`      <section id="works" className="bg-gray-50 dark:bg-gray-950 py-10 sm:py-16">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4">`);
lines.push(`          <div className="text-center mb-8 sm:mb-10">`);
lines.push(`            <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-2">So&apos;nggi bajarilgan ishlar</h2>`);
lines.push(`            <p className="text-gray-500 dark:text-gray-400 text-sm sm:text-base">Mijozlarimizning muvaffaqiyatli buyurtmalari</p>`);
lines.push(`          </div>`);
lines.push(`          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5">`);
lines.push(`            {completedWorks.map((w, i) => (`);
lines.push(`              <div key={i} className="bg-white dark:bg-gray-900 rounded-2xl p-5 shadow-sm border border-gray-100 dark:border-gray-800 hover:shadow-md transition">`);
lines.push(`                <div className="flex items-center justify-between mb-3">`);
lines.push(`                  <span className="bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400 text-xs font-semibold px-2.5 py-1 rounded-full flex items-center gap-1">`);
lines.push(`                    <CheckCircle2 className="w-3.5 h-3.5" /> Tugallangan`);
lines.push(`                  </span>`);
lines.push(`                  <div className="flex gap-0.5">`);
lines.push(`                    {[...Array(w.rating)].map((_, j) => (`);
lines.push(`                      <Star key={j} className="w-3.5 h-3.5 text-yellow-400 fill-yellow-400" />`);
lines.push(`                    ))}`);
lines.push(`                  </div>`);
lines.push(`                </div>`);
lines.push(`                <h3 className="font-semibold text-gray-900 dark:text-white mb-1">{w.title}</h3>`);
lines.push(`                <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">{w.category}</p>`);
lines.push(`                <div className="flex items-center justify-between text-xs text-gray-400">`);
lines.push(`                  <span className="flex items-center gap-1"><Award className="w-3.5 h-3.5" /> {w.master}</span>`);
lines.push(`                  <span className="flex items-center gap-1"><MapPin className="w-3.5 h-3.5" /> {w.location}</span>`);
lines.push(`                </div>`);
lines.push(`              </div>`);
lines.push(`            ))}`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== CTA ===== */}`);
lines.push(`      <section className="bg-gradient-to-r from-blue-600 to-indigo-700 py-10 sm:py-16">`);
lines.push(`        <div className="max-w-3xl mx-auto px-4 text-center text-white">`);
lines.push(`          <h2 className="text-2xl sm:text-3xl font-bold mb-3 sm:mb-4">Tayyor? Hoziroq boshlang!</h2>`);
lines.push(`          <p className="text-blue-100 mb-6 sm:mb-8 text-sm sm:text-base">`);
lines.push(`            Ro&apos;yxatdan o&apos;ting va daqiqalar ichida ishonchli usta toping yoki o&apos;zingiz usta sifatida ishlang.`);
lines.push(`          </p>`);
lines.push(`          <div className="flex flex-col sm:flex-row flex-wrap justify-center gap-3 sm:gap-4">`);
lines.push(`            <Link href="/auth/register" className="inline-flex items-center justify-center gap-2 bg-white text-blue-700 font-semibold px-6 sm:px-8 py-3 sm:py-3.5 rounded-xl hover:bg-blue-50 transition shadow-lg text-sm sm:text-base">`);
lines.push(`              <UserPlus className="w-5 h-5" /> Ro&apos;yxatdan o&apos;tish`);
lines.push(`            </Link>`);
lines.push(`            <Link href="/auth/login" className="inline-flex items-center justify-center gap-2 bg-white/15 backdrop-blur text-white font-semibold px-6 sm:px-8 py-3 sm:py-3.5 rounded-xl hover:bg-white/25 transition border border-white/20 text-sm sm:text-base">`);
lines.push(`              <LogIn className="w-5 h-5" /> Kirish`);
lines.push(`            </Link>`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </section>`);
lines.push(``);
lines.push(`      {/* ===== FOOTER ===== */}`);
lines.push(`      <footer className="bg-gray-900 text-gray-400 py-10">`);
lines.push(`        <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row items-center justify-between gap-4">`);
lines.push(`          <div className="flex items-center gap-2.5">`);
lines.push(`            <img src="/logo.png" alt="Online Usta" className="object-contain h-8 w-auto logo-white" />`);
lines.push(`            <span className="font-bold text-white">Online Usta</span>`);
lines.push(`          </div>`);
lines.push(`          <p className="text-sm text-center">&copy; 2026 Online Usta. Barcha huquqlar himoyalangan.</p>`);
lines.push(`          <div className="flex items-center gap-4 text-sm">`);
lines.push(`            <a href="#" className="hover:text-white transition">Foydalanish shartlari</a>`);
lines.push(`            <a href="#" className="hover:text-white transition">Aloqa</a>`);
lines.push(`          </div>`);
lines.push(`        </div>`);
lines.push(`      </footer>`);
lines.push(`    </div>`);
lines.push(`  );`);
lines.push(`}`);

const content = lines.join('\n');
fs.writeFileSync(filePath, content, 'utf8');
console.log('SUCCESS! Written', content.length, 'chars,', lines.length, 'lines to', filePath);
